/**
 * parameters of any given pets object
 * @typedef {Object} pet
 * @param {string} pet.name
 * @param {number} pet.id
 * @param {boolean} pet.fixed
 * @param {string} pet.microchip_num
 * @param {string} pet.summary
 * @param {string} pet.type
 * @param {string} pet.breed
 * @param {string} pet.sex
 * @param {string} pet.color
 * @param {string} pet.age
 * @param {string[]} pet.health_info
 */

/**
 * @type {pet[]}
 */
const pets = [
  {
    name: "Baxter",
    id: 34621,
    fixed: true,
    microchip_num: "982000364789210",
    summary:
      "Meet Baxter, a lovable Beagle with a knack for sniffing out fun! Baxter was rescued from a shelter and has blossomed into a friendly and outgoing boy. He loves long walks and has a keen sense of smell. He's great with kids and other dogs, making him the perfect family pet. His favorite pastime is chasing squirrels in the park and curling up for naps.",
    type: "Dog",
    breed: "Beagle",
    sex: "Male",
    color: "Tri-color (Black, Brown, White)",
    age: "5 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/34621.jpg",
  },
  {
    name: "Luna",
    id: 57281,
    fixed: true,
    microchip_num: "981120019776432",
    summary:
      "Luna is a majestic Maine Coon with a fluffy grey coat and striking white markings. She was found as a stray and has since become a gentle and affectionate companion. Luna enjoys perching on windowsills, watching birds, and being the center of attention. She's a bit shy at first but warms up quickly, especially if you have treats! Luna would thrive in a calm environment where she can relax and be pampered like the queen she is.",
    type: "Cat",
    breed: "Maine Coon",
    sex: "Female",
    color: "Grey with white markings",
    age: "3 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/57281.jpg",
  },
  {
    name: "Sandy",
    id: 41382,
    fixed: true,
    microchip_num: "985112004567890",
    summary:
      "Sandy is a heartwarming Golden Retriever with a golden coat as bright as her personality. Rescued from a neglectful situation, she has shown incredible resilience and love for life. Sandy is great with children and other pets, making her an ideal family dog. She enjoys outdoor adventures, especially swimming and fetching. Sandy is looking for a forever home where she can spread her joy and love.",
    type: "Dog",
    breed: "Golden Retriever",
    sex: "Female",
    color: "Golden",
    age: "7 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/41382.jpg",
  },
  {
    name: "Oliver",
    id: 62894,
    fixed: true,
    microchip_num: "981120025678902",
    summary:
      "Oliver is a sleek Siamese cat with striking blue eyes and a seal point coat. Found wandering in a neighborhood, he's adapted well to shelter life but is eager for a permanent home. Oliver is vocal, expressing his thoughts freely, and enjoys interactive playtime. He's affectionate and loves to be close to his human companions, often following them around the house. Oliver would do best in a home where he can receive plenty of attention and love.",
    type: "Cat",
    breed: "Siamese",
    sex: "Male",
    color: "Seal Point",
    age: "2 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/62894.jpg",
  },
  {
    name: "Max",
    id: 47920,
    fixed: true,
    microchip_num: "985120031478902",
    summary:
      "Max is a charming Chocolate Labrador with a love for life and a tail that never stops wagging. Rescued from an overcrowded shelter, Max has shown immense gratitude and loyalty to his caregivers. He is full of energy and would thrive in a home with a backyard or regular access to outdoor activities. Max is great with children and other dogs, and he's always up for a game of fetch or a leisurely walk. His ideal home would be with an active family who can match his energy and zest for life.",
    type: "Dog",
    breed: "Labrador Retriever",
    sex: "Male",
    color: "Chocolate",
    age: "4 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/47920.jpg",
  },
  {
    name: "Daisy",
    id: 58329,
    fixed: true,
    microchip_num: "981120036712345",
    summary:
      "Daisy is a stunning white Persian cat with a luxurious coat and gentle demeanor. She was surrendered by an owner who could no longer care for her. Daisy is a bit of a diva and loves being the center of attention. She enjoys being groomed and will happily sit in your lap for hours. She's not fond of loud noises or fast movements, so a quiet and calm household would be ideal. Daisy is looking for a loving home where she can be pampered and adored.",
    type: "Cat",
    breed: "Persian",
    sex: "Female",
    color: "White",
    age: "6 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/58329.jpg",
  },
  {
    name: "Charlie",
    id: 49583,
    fixed: true,
    microchip_num: "982000367829101",
    summary:
      "Charlie is a spirited Dapple Dachshund with a playful personality. He was found as a stray and has since shown an incredible zest for life. Charlie loves exploring, whether it's a new trail or the corners of his home. He's a bit mischievous and enjoys hiding his toys. Charlie would do well in a home with an individual or family who enjoys fun and adventure. He's small but has a big heart and a lot of love to give.",
    type: "Dog",
    breed: "Dachshund",
    sex: "Male",
    color: "Dapple (Black and Gray)",
    age: "3 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/49583.jpg",
  },
  {
    name: "George",
    id: 61029,
    fixed: true,
    microchip_num: "985112007651234",
    summary:
      "George is a robust British Shorthair with a striking blue-gray coat and a calm, dignified demeanor. Rescued from a busy city environment, he's adapted well to a quieter life. George enjoys leisurely days, lounging in sunny spots, and watching the world go by. He's not overly demanding for attention but appreciates a good chin scratch and will purr loudly in response. George is a bit reserved at first but becomes a loyal companion once he feels comfortable. He would be perfect for someone seeking a low-maintenance, independent cat.",
    type: "Cat",
    breed: "British Shorthair",
    sex: "Male",
    color: "Blue (Gray)",
    age: "4 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/61029.jpg",
  },
  {
    name: "Bella",
    id: 50824,
    fixed: true,
    microchip_num: "982000360234567",
    summary:
      "Bella is a spirited Boxer with a fawn coat and charming white markings. She was rescued from a neglectful situation and has shown immense love and gratitude to her caregivers. Bella is energetic and playful, enjoying activities like running and playing fetch. She's great with older children and would thrive in a home where she can be active and engaged. Bella has a big personality and would be a fantastic companion for someone who loves adventure and fun.",
    type: "Dog",
    breed: "Boxer",
    sex: "Female",
    color: "Fawn with white markings",
    age: "6 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/50824.jpg",
  },
  {
    name: "Sophie",
    id: 63845,
    fixed: true,
    microchip_num: "985112008765432",
    summary:
      "Sophie is a young Ragdoll cat with a soft seal point coat and mesmerizing blue eyes. She was found as a kitten and raised in a foster home. Sophie is incredibly affectionate, often seeking out laps to curl up in. She's playful and enjoys interactive toys, but she's also content to relax and watch the world go by. Sophie gets along well with other pets and would be an excellent addition to a loving family or individual looking for a gentle and loving companion.",
    type: "Cat",
    breed: "Ragdoll",
    sex: "Female",
    color: "Seal point with blue eyes",
    age: "1 Year",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/63845.jpg",
  },
  {
    name: "Milo",
    id: 70123,
    fixed: true,
    microchip_num: "982001234567890",
    summary:
      "Milo is an adventurous Tabby cat with a vibrant orange coat. He's curious and loves to explore every nook and cranny of his environment. Rescued from a busy street, Milo has adapted well to indoor life but still enjoys gazing out the window. He's playful and enjoys interactive toys, making him a delightful companion. Milo would fit well in an active household where he can satisfy his curiosity and play to his heart's content.",
    type: "Cat",
    breed: "Tabby",
    sex: "Male",
    color: "Orange",
    age: "2 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/70123.jpg",
  },
  {
    name: "Zoe",
    id: 70234,
    fixed: true,
    microchip_num: "982002345678901",
    summary:
      "Zoe is a vivacious Border Collie with a fluffy black and white coat. Known for her intelligence and agility, she excels in training and loves to learn new tricks. Rescued from a farm that could no longer keep her, Zoe is full of energy and thrives in an active environment. She's social and gets along well with other dogs, making her an excellent addition to a multi-pet household or as a companion for outdoor adventures.",
    type: "Dog",
    breed: "Border Collie",
    sex: "Female",
    color: "Black and White",
    age: "3 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/70234.jpg",
  },
  {
    name: "Jasper",
    id: 70345,
    fixed: true,
    microchip_num: "982003456789012",
    summary:
      "Jasper is a sleek Russian Blue cat with a gleaming silver-blue coat. He's reserved but affectionate, preferring quiet companionship and gentle petting. Found as a stray in a quiet neighborhood, Jasper has embraced domestic life with grace. He's low-maintenance, enjoying his independence but also seeking out cozy laps when in the mood. Jasper would be ideal for someone seeking a calm and dignified feline friend.",
    type: "Cat",
    breed: "Russian Blue",
    sex: "Male",
    color: "Silver-Blue",
    age: "4 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/70345.jpg",
  },
  {
    name: "Emma",
    id: 70456,
    fixed: true,
    microchip_num: "982004567890123",
    summary:
      "Emma is a gentle Cocker Spaniel with a silky golden coat. She's sweet-natured and loves being around people, making her an excellent family pet. Emma was surrendered by an owner who could no longer care for her, and she's adapted well to shelter life. She enjoys leisurely walks and quiet evenings by her human's side. Emma would thrive in a loving home that can offer her the affection and attention she deserves.",
    type: "Dog",
    breed: "Cocker Spaniel",
    sex: "Female",
    color: "Golden",
    age: "5 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/70456.jpg",
  },
  {
    name: "Rocky",
    id: 70567,
    fixed: true,
    microchip_num: "982005678901234",
    summary:
      "Rocky is a robust American Bulldog with a muscular build and a heart of gold. He has a protective nature but is gentle with his family. Rescued from a difficult situation, Rocky has shown immense loyalty and affection to those who care for him. He enjoys physical activities and would do best in a home with a yard. Rocky is looking for a forever home that can provide him with love, structure, and plenty of exercise.",
    type: "Dog",
    breed: "American Bulldog",
    sex: "Male",
    color: "White with Brindle patches",
    age: "4 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/70567.jpg",
  },
  {
    name: "Ivy",
    id: 70678,
    fixed: true,
    microchip_num: "982006789012345",
    summary:
      "Ivy is a captivating Sphynx cat known for her hairless skin and large, expressive eyes. She's outgoing and loves to be the center of attention, thriving in an environment where she can interact with people and other pets. Found in a loving but overwhelmed household, Ivy is accustomed to being pampered and seeks a home that understands the care needs of her unique breed. She's affectionate, playful, and sure to bring a unique charm to her new home.",
    type: "Cat",
    breed: "Sphynx",
    sex: "Female",
    color: "Pink",
    age: "3 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/70678.jpg",
  },
  {
    name: "Theo",
    id: 70789,
    fixed: true,
    microchip_num: "982007890123456",
    summary:
      "Theo is a playful Pomeranian with a fluffy coat and an energetic spirit. He's small in size but has a big personality, always ready to play and explore. Rescued from a neglectful home, Theo has bounced back with resilience and joy. He's great with other small pets and enjoys being part of a family. Theo is looking for a loving home where he can be the center of attention and showered with affection.",
    type: "Dog",
    breed: "Pomeranian",
    sex: "Male",
    color: "Orange",
    age: "2 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/70789.jpg",
  },
  {
    name: "Willow",
    id: 70890,
    fixed: true,
    microchip_num: "982008901234567",
    summary:
      "Willow is a serene and beautiful Norwegian Forest cat with a luxurious long coat and a love for climbing. Rescued from a cold climate, she's adapted well to indoor life but still appreciates a good high perch. She's gentle, with a soft voice, and enjoys interactive play as well as quiet time in a sunny window. Willow would be a perfect companion in a quiet, loving home that appreciates her calm presence and stunning appearance.",
    type: "Cat",
    breed: "Norwegian Forest",
    sex: "Female",
    color: "Gray",
    age: "5 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/70890.jpg",
  },
  {
    name: "Leo",
    id: 70901,
    fixed: true,
    microchip_num: "982009012345678",
    summary:
      "Leo is a confident and charismatic German Shepherd with a striking black and tan coat. He's intelligent, loyal, and protective, making him an excellent family pet and guardian. Leo was rescued from a situation where he couldn't be properly cared for, showing immense gratitude towards his rescuers. He thrives on activity and mental stimulation and would fit best in an active home that can provide him with training, love, and plenty of exercise.",
    type: "Dog",
    breed: "German Shepherd",
    sex: "Male",
    color: "Black and Tan",
    age: "3 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/70901.jpg",
  },
  {
    name: "Ruby",
    id: 71012,
    fixed: true,
    microchip_num: "982010123456789",
    summary:
      "Ruby is a lively Jack Russell Terrier with boundless energy and a sparkling personality. She's small but mighty, with a white and tan coat that matches her adventurous spirit. Ruby was found wandering and quickly won over the hearts of her rescuers with her bravery and zest for life. She's great with kids and other pets, making her an ideal addition to a lively family. Ruby is looking for a home that can match her energy and spirit of adventure.",
    type: "Dog",
    breed: "Jack Russell Terrier",
    sex: "Female",
    color: "White and Tan",
    age: "2 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/71012.jpg",
  },
  {
    name: "Gizmo",
    id: 71123,
    fixed: true,
    microchip_num: "982011234567890",
    summary:
      "Gizmo is an adorable Shih Tzu with a lovable personality and a soft, fluffy coat. He's friendly and enjoys being with people, making him a great companion for families or singles. Rescued from a neglectful situation, Gizmo has shown no shortage of affection and loyalty to those who care for him. He enjoys leisurely walks, cuddles, and playtime with toys. Gizmo is looking for a forever home where he can continue to spread joy and receive the love he deserves.",
    type: "Dog",
    breed: "Shih Tzu",
    sex: "Male",
    color: "White and Grey",
    age: "4 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/71123.jpg",
  },
  {
    name: "Aurora",
    id: 71234,
    fixed: true,
    microchip_num: "982012345678901",
    summary:
      "Aurora is a majestic Bengal cat with a striking spotted coat that mirrors the wild beauty of her breed. She's active, intelligent, and loves to play, offering the perfect blend of independence and companionship. Aurora was surrendered by an owner who could no longer meet her needs, thriving in an environment where she can climb and explore. She's best suited for a home with previous cat experience and plenty of space for her adventures.",
    type: "Cat",
    breed: "Bengal",
    sex: "Female",
    color: "Spotted",
    age: "3 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/71234.jpg",
  },
  {
    name: "Bailey",
    id: 71345,
    fixed: true,
    microchip_num: "982013456789012",
    summary:
      "Bailey is a gentle and loving Golden Doodle who combines the intelligence of a Poodle with the affability of a Golden Retriever. His soft, curly coat and kind eyes reflect his friendly nature. Bailey was rescued from a crowded home and is looking for a loving family that appreciates his gentle demeanor. He's great with children and other animals, making him a wonderful addition to any home.",
    type: "Dog",
    breed: "Golden Doodle",
    sex: "Male",
    color: "Cream",
    age: "2 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/71345.jpg",
  },
  {
    name: "Misty",
    id: 71456,
    fixed: true,
    microchip_num: "982014567890123",
    summary:
      "Misty is a sleek and mysterious black cat with a glossy coat and piercing green eyes. She embodies the elegance and mystery of her coloring, being both independent and affectionate. Misty was rescued from a high-traffic area, proving herself to be adaptable and resilient. She enjoys her quiet time as much as her playful moments and would be a perfect fit for a home looking for a cat with a balanced temperament.",
    type: "Cat",
    breed: "Domestic Shorthair",
    sex: "Female",
    color: "Black",
    age: "3 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/71456.jpg",
  },
  {
    name: "Buddy",
    id: 71567,
    fixed: true,
    microchip_num: "982015678901234",
    summary:
      "Buddy is a friendly and energetic Beagle mix with a keen nose and a love for adventure. His tricolor coat and eager eyes are always ready for the next fun activity. Rescued from a shelter where he was overlooked, Buddy has proven to be a loyal and joyful companion. He's great with families, enjoying both the great outdoors and cozy indoor time. Buddy is searching for a home where he can be an integral part of the family's adventures.",
    type: "Dog",
    breed: "Beagle Mix",
    sex: "Male",
    color: "Tri-color",
    age: "4 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/71567.jpg",
  },
  {
    name: "Lily",
    id: 71678,
    fixed: true,
    microchip_num: "982016789012345",
    summary:
      "Lily is a graceful and elegant Siamese mix with striking blue eyes and a sleek, cream-colored coat. She's vocal and communicative, loving to share her thoughts with her human companions. Lily was found in a community garden, showing a friendly disposition towards all. She's affectionate and enjoys being part of a family, fitting well in a home that enjoys the interactive and engaging nature of Siamese cats.",
    type: "Cat",
    breed: "Siamese Mix",
    sex: "Female",
    color: "Cream and Brown",
    age: "2 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/71678.jpg",
  },
  {
    name: "Rex",
    id: 71789,
    fixed: true,
    microchip_num: "982017890123456",
    summary:
      "Rex is a majestic and powerful Rottweiler with a commanding presence and a heart of gold. His deep brown eyes reflect his intelligence and loyalty. Rescued from an uncertain future, Rex has shown immense gratitude and affection towards his caregivers. He's protective yet gentle, making him an excellent companion for a family with space for him to roam. Rex is looking for a forever home that can provide him with love, structure, and the companionship he craves.",
    type: "Dog",
    breed: "Rottweiler",
    sex: "Male",
    color: "Black and Tan",
    age: "5 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/71789.jpg",
  },
  {
    name: "Piper",
    id: 71890,
    fixed: true,
    microchip_num: "982018901234567",
    summary:
      "Piper is a charming and spirited Australian Shepherd with a beautiful merle coat and bright, attentive eyes. Known for her intelligence and agility, Piper loves to learn and is quick on her feet. She was surrendered by a family who could no longer give her the attention she needs. Piper thrives in an environment where she can exercise her mind and body, making her perfect for someone with an active lifestyle or interest in training.",
    type: "Dog",
    breed: "Australian Shepherd",
    sex: "Female",
    color: "Merle",
    age: "3 Years",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/71890.jpg",
  },
  {
    name: "Felix",
    id: 71901,
    fixed: true,
    microchip_num: "982019012345678",
    summary:
      "Felix is a playful and curious Domestic Longhair cat with a fluffy coat and an adventurous spirit. He's sociable and enjoys being around both humans and other pets. Found as a young stray, Felix quickly adapted to indoor life, showing a preference for cozy naps in laps and playful antics with toys. He's looking for a home that can offer him the affection and stimulation he needs to thrive.",
    type: "Cat",
    breed: "Domestic Longhair",
    sex: "Male",
    color: "Black and White",
    age: "1 Year",
    health_info: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    image: "./images/pets/71901.jpg",
  },
];
